#!/bin/bash

VM_NAME=${1:-"controlvm"}
shift
EXEC_COMMAND="$@"

SSH_PORT=$(vagrant ssh-config ${VM_NAME} | grep Port | awk '{print $2}') || { echo "failed to get ssh port of vm ${VM_NAME} "; exit 1 ; }
if [ -z "${EXEC_COMMAND}" ] ; then
  sshpass -p vagrant \
      ssh -p ${SSH_PORT} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vagrant@127.0.0.1
else
  echo "exec commmand: ${EXEC_COMMAND}"
  sshpass -p vagrant \
      ssh -p ${SSH_PORT} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vagrant@127.0.0.1 "${EXEC_COMMAND}"
fi
